config/routes.rb
Rails.application.routes.draw do
  get 'cart/show'
resources :order_items
  get 'cart', to: 'cart#show'
  get 'search', to: 'menu#search'
  resources :categories
  get 'menu', to: 'menu#index'
  devise_for :users
  resources :products
  resources :charges
  root 'pages#home'
  get 'catering', to: 'pages#catering'
  get 'info', to: 'pages#info'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :set_cats

  def index
  @page = 'menu'
  @products = Product.all
  @order_item = current_order.order_items.new
  end

  def search
  query = params[:search]

  results = Product.where('name LIKE ?', "%#{query}%")
  if params[:filter] == 'Select Filter'
  @products = results
  else
  # Converts 'Dairy Free' to 'Dairy_Free' -> 'dairy_free' -> :dairy_free
  symbol = params[:filter].gsub(/ /, '_').downcase!.to_sym
  @products = results.where(symbol => true)
  end
  end



  private 
  def set_cats
  @cats = Category.all.where(display: true)
  end
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/menu/_products.html.erb
<div class="row">
<% @cats.each do |cat| %>
<% if cat.products.where(featured: true).first.image.attached? %>
<%= image_tag(cat.products.where(featured: true).first.image, class:'img-fluid') %>
<% end %>
<div class="col-12">
<h1 style="text-align:center;"><%= cat.heading %></h1>
<hr />
</div>
<% @products.each do |product| %>
<% if product.category == cat %>
<div class="col-4">
<h5>
<%= product.name %>
</h5>
<p>
<%= product.description %>
</p>
<span><%= product.price %>  <%=  "| Available for catering" if product.catering %></span>
<%= form_with model: @order_item do |f| %>
<%= f.hidden_field :product_id, value: product.id %>
<%= f.number_field :quantity, value: 0, min: 1 %>

<%= f.submit "Add to Cart" %>
<%= link_to "Proceed to Checkout", cart_path %>
<% end %>
</div>
<% end %>
<% end %>
<% end %>
</div>


app/views/menu/index.html.erb
<div class="menu-container">
	<div class="row">
		<div class="col-12">
		<%= render 'layouts/title'%>
				<%= form_tag(search_path, method: "get", remote: true) do %>
				<div class="input-group mb-5">
					<div class="col-8" style="padding:0">
					<%= text_field_tag :search, '', class:'form-control', placeholder: 'Search..', onkeydown:'clickSubmit();'%>
					</div>
					<div class="col-4" style="padding:0">
					<%= select_tag "filter", options_for_select(['Select Filter', 
					'Dairy Free', 
					'Gluten Free', 
					'Kosher', 
					'Peanut Free', 
					'Vegan', 
					'Vegetarian']), class:'custom-select', onchange:'clickSubmit()' %>
					
					
					<%= submit_tag "Search", class:'btn btn-dark', id:'search_submit', style:'display:none' %>
					</div>
				</div>
				<% end %>
			</div>
		</div>
		<div id="menu-products-container">
		<%= render 'menu/products' %>
		</div>
	</div>
	

app/views/menu/search.js.erb
$("#menu-products-container").html("<%= j render 'menu/products' %>");