config/routes.rb
Rails.application.routes.draw do
  get 'cart/show'
resources :order_items
  get 'cart', to: 'cart#show'
  get 'search', to: 'menu#search'
  resources :categories
  get 'menu', to: 'menu#index'
  devise_for :users
  resources :products
  resources :charges
  root 'pages#home'
  get 'catering', to: 'pages#catering'
  get 'info', to: 'pages#info'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
has_many :products, dependent: :delete_all
end

app/models/order.rb
class Order < ApplicationRecord
has_many :order_items
before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
belongs_to :product
belongs_to :order
before_save :set_unit_price
before_save :set_total

def unit_price
# If there is a record
if persisted?
self[:unit_price]
else
product.price
end
end

  def total
    unit_price * quantity
  end

private
def set_unit_price
self[:unit_price] = unit_price
end

def set_total
self[:total] = total * quantity
end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_one_attached :image
  has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
  @order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:heading, :body, :display)
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'usd',
  })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :set_cats

  def index
  @page = 'menu'
  @products = Product.all
  @order_item = current_order.order_items.new
  end

  def search
  query = params[:search]

  results = Product.where('name LIKE ?', "%#{query}%")
  if params[:filter] == 'Select Filter'
  @products = results
  else
  # Converts 'Dairy Free' to 'Dairy_Free' -> 'dairy_free' -> :dairy_free
  symbol = params[:filter].gsub(/ /, '_').downcase!.to_sym
  @products = results.where(symbol => true)
  end
  end



  private 
  def set_cats
  @cats = Category.all.where(display: true)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @page = 'home'
  end

  def catering
  @page = 'catering'
  end

  def info
  @page = 'info'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :check_categories, only: %i[new create edit]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.category = Category.find(params[:product][:category_id])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
  @product.category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


  def check_categories
    redirect_to new_category_path if Category.count == 0
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image, :category_id, :dairy_free, :gluten_free, :kosher, :peanut_free, :vegan, :vegetarian, :available, :catering, :featured)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
def current_order
#Use find by ID
if Order.find_by_id(session[:order_id]).nil?
Order.new
else
Order.find_by_id(session[:order_id])
end
end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_links.html.erb
<div class="col-2">
<h5 class="link-container">
<%= link_to "Home", root_path, class: "link #{@page == 'home' ? 'active' : ''} "%>
</h5>
<h5 class="link-container">
<%= link_to "Menu", menu_path, class: "link #{@page == 'menu' ? 'active' : ''} "%>
</h5>
<h5 class="link-container">
<%= link_to "Catering", catering_path, class: "link #{@page == 'catering' ? 'active' : ''} "%>
</h5>
<h5 class="link-container">
<%= link_to "More Info", info_path, class: "link #{@page == 'info' ? 'active' : ''} "%>
</h5>
<h5 class="link-container">
<%= link_to "Customer Reviews", "", class: "link #{@page == 'reviews' ? 'active' : ''} "%>
</h5>
</div>

app/views/layouts/_title.html.erb
<div class="title-card">
<h1 class="title-text">
Lily's Bistro
</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'src/application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
</head>

<body>

    <div class="<%= @page %>-page">
        <div class="row page-container">
            <%= render 'layouts/links'%>
            <div class="col-8">

                <%= yield %>
            </div>
            <div class="col-2"></div>
        </div>
    </div>

</body>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/catering.html.erb

<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>



<div class="catering-container">
  <div class="content">
    <h1>Heading</h1>
    <p>Lorem ipsum dolor sit amet, an his etiam torquatos. Tollit soleat phaedrum te duo, eum cu recteque expetendis neglegentur. Cu mentitum maiestatis persequeris pro, pri ponderum tractatos ei.</p>
  </div>
</div>

</body>
</html>

app/views/pages/home.html.erb
<div class="col-8"></div>